### ISSUE TITLE
Synchronization from external database failed when unit value differs

### ISSUE THREAD

**Issue by kidhab** [foodcoops/foodsoft#1014]
This is actually a users feedback that I was able to reproduce via our [demo](https://demo.foodcoops.net) instance.

Trying to synchronise the supplier database with the external source failed with a ZeroDivisionError:
```
Completed 500 Internal Server Error in 69ms (ActiveRecord: 36.5ms | Allocations: 6684)
[...]
FATAL -- : [95b7f1ef-f999-43e3-aa1e-8b52f315acf9]   
ZeroDivisionError (ZeroDivisionError):
[95b7f1ef-f999-43e3-aa1e-8b52f315acf9] app/models/article.rb:215:in `convert_units'
[95b7f1ef-f999-43e3-aa1e-8b52f315acf9] app/models/article.rb:137:in `unequal_attributes'
[95b7f1ef-f999-43e3-aa1e-8b52f315acf9] app/models/article.rb:117:in `shared_article_changed?'
[95b7f1ef-f999-43e3-aa1e-8b52f315acf9] app/models/supplier.rb:50:in `block in sync_all'
[95b7f1ef-f999-43e3-aa1e-8b52f315acf9] app/models/supplier.rb:44:in `sync_all'
```

The error occurs when the unit field contains a comma seperated weight (e.g. "kg" or "g") value which differs from the value of the external database - if it also contains a weight specification.

There's no error if you remove the weight specification. So I assume it's caused by the [conversion](https://github.com/foodcoops/foodsoft/blob/master/app/models/article.rb#L215).

You can reproduce [here](https://demo.foodcoops.net/demo/suppliers/3/articles).

The screenshot shows the problematic unit field of "Article1":

![Bildschirmfoto vom 2023-06-21 22-05-19](https://github.com/foodcoops/foodsoft/assets/32387157/266182b4-70d2-4f82-a916-8fafdb7bdc5e)

And the related Article in the shared database:

![Bildschirmfoto vom 2023-06-21 22-10-09](https://github.com/foodcoops/foodsoft/assets/32387157/4871c217-bfef-4914-b174-2e18a3729e03)

**Comment by yksflip** [comment]
awesome bug hunting kidhab!
Could it be possible that in  `conversion_factor = (supplier_unit / fc_unit).to_base.to_r`  fc_unit is zero ?

**Comment by yksflip** [comment]
soo for some reason Unit.new("0,9kg") becomes 0 ... 
I fixed it by adding 0 checks to the convert_units function. The same exception could be reproduced by simply setting Unit to "0kg" ...
Not sure if we'd want to maybe replace "," to "." or explain the user  that only "." is allowed
