### ISSUE TITLE
[feature] Show the recipients in the thread view of messages

### ISSUE THREAD

**Issue by TomStrom16** [foodcoops/foodsoft#1035]
In the single message view a user sees the list of recipients.

I'm missing this feature in the thread view so I added it and created a Pull-Request: https://github.com/foodcoops/foodsoft/pull/1034

Not sure how to handle translations, so I just added as much as possible to the translation files :-)

Please review/comment/merge :-)

[edit] looks like I'm not allowed to add labels by mself? This would be a feature/usability?

**Comment by yksflip** [comment]
awesome, thanks!
