### ISSUE TITLE
migrate invoice attachments to active storage (slow performance financial links)

### ISSUE THREAD

**Issue by mjavurek** [foodcoops/foodsoft#1037]
Our Foodsoft database contains a constantly rising number of invoices with attachments (PDF, JPEG). The following operations have become continuously slower and slower over the years and last now approx 2 to 3 minutes:
* Display unpaid invoices (unbezahlte Rechnungen anzeigen), 
* Create/display financial link (Finanzlink erstellen/anzeigen)
* add invoice or Foodsoft transactions to financial link
* Assign Foodsoft transactions to Bank transactions (Bank Konto Transaktionen zuordnen)

I remember @paroga mentioned that the source of the problem is that the invoice attachment files are stored in the database instead of as separate files which should be fixed in order to keep the Foodsoft performance also for increasing number of invoices with attachments.

**Comment by yksflip** [comment]
Thanks for raising this issue mjavurek!
It sounds very likely to be the source of the problem. There was recently added support for filesystem storage. I think it should be possible to migrate the invoice attachments to active storage too.
I'll put it on the roadmap.

**Comment by yksflip** [comment]
gave it a first tryout in: #1039
