### ISSUE TITLE
Finance ordergroup balance sums are misleading + performance issue

### ISSUE THREAD

**Issue by twothreenine** [foodcoops/foodsoft#1044]
The feature introduced in #1017 as requested in #382 takes the sum of all transactions of a certain transaction class.
However, these include _foodcoop transactions_ as well as transactions from deleted ordergroups, with both aren't listed in the table.

I've reproduced this in the [international demo](https://demo.foodcoops.net/demo/finance/ordergroups) by 
1. creating a foodcoop transaction of 20 € (transaction class Standard)
2. creating an ordergroup deletion test, granting 100 € (transaction class Standard), then deleting the ordergroup

Now, the sum of _Standard_ doesn't match the values above it (should be 110 €, but is 230 €).
![grafik](https://github.com/foodcoops/foodsoft/assets/22921479/63580083-501b-4087-8570-11833fd580b9)

The "total" value suggests to be the sum of the values above, so I think both _foodcoop transactions_ and _transactions from deleted ordergroups_ should be excluded from this calculation. For my understanding of foodcoop transactions, it wouldn't make sense to include a `Foodcoop` ordergroup in this table.

Performance:
I also noticed that, in Foodsofts with a lot of transactions over many years, this menu loads significantly slower now (takes more than 20 s in ours.) Also each time when I switch between page sizes (20/50/100/500) or between pages.

**Comment by yksflip** [comment]
wow, thank you. No idea why I didn't think about that. Also I completely ignored the filtering/pagination ... I think I found a good solution in #1051 for that. It should also improve the performance. 
Would you like to give that a test before I merge it? :)
