### ISSUE TITLE
Dev seed (small.en) leads to error

### ISSUE THREAD

**Issue by twothreenine** [foodcoops/foodsoft#1049]
When I try to set Foodsoft up for development via Docker and run
```
docker compose -f docker-compose-dev.yml run --rm foodsoft \
  bundle exec rake db:schema:load db:seed:small.en
```

I get

```
ActiveRecord::InvalidForeignKey: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
```

This can be solved by:
1. skipping this step and starting the container, accessing `http://localhost:2080` (phpMyAdmin) and deleting all tables (development -> select all tables -> delete)
2. There's an error that `active_storage_blobs` couldn't be deleted (similar error as above), trying again to delete all tables succeeds
... and then I forgot how we solved it

**Comment by yksflip** [comment]
yeah I can reproduce this error. Look's like that the `FinancialTransactionClass` is already created somewhere else and then this fails in the seed as the key/name is already taken

**Comment by lentschi** [comment]
It seems that `rake db:schema:load` is _not_ intended to always succeed for existing dbs - see discussion here:
https://github.com/rails/rails/issues/41491

Since `rake foodsoft:setup_development_docker` already ran `rake db:setup` (which includes schema loading and minimal seeding) it cannot be run again without first emptying the db.

**Comment by yksflip** [comment]
ah okay, so we could either try to rewrite the seeds to check whether these initial records already exists (`find_or_create_by` doesn't work with the uniqueness constraint somehow..., but `first_or_create` worked for me) or we add a note to the docs that you'd have to recreate a plain database first before loading seeds
