### ISSUE TITLE
apple-touch-icon

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodsoft#130]
With people using iPads, iPhones and similar products from other brands, I get a lot of messages like this in my log/production.log:

```
ActionController::RoutingError (No route matches [GET] "/images/apple-touch-icon.png"):
```

I think it would be nice to have a default touch icon, as well as get rid of the useless error messages. http://mathiasbynens.be/notes/touch-icons

**Comment by carchrae** [comment]
i'm still getting bogus (404) errors emailed to me.  i don't like this because it hides real errors - (it takes some scanning to realise this is an error caused by a lack of `apple-touch-icon`)  

https://stackoverflow.com/questions/12480497/why-am-i-getting-error-for-apple-touch-icon-precomposed-png


```
An ActionView::MissingTemplate occurred in home#index:

  Missing template home/index, application/index with {:locale=>[:en], :formats=>[:png], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :haml]}. Searched in:
  * "/home/foodsoft/foodsoft/app/views"
  * "/home/foodsoft/foodsoft/plugins/documents/app/views"
  * "/home/foodsoft/foodsoft/plugins/messages/app/views"
  * "/home/foodsoft/foodsoft/plugins/wiki/app/views"
  * "/home/foodsoft/.rvm/gems/ruby-2.6.6/gems/twitter-bootstrap-rails-2.2.8/app/views"
  * "/home/foodsoft/.rvm/gems/ruby-2.6.6/gems/doorkeeper-5.0.3/app/views"
  * "/home/foodsoft/.rvm/gems/ruby-2.6.6/gems/kaminari-core-1.2.0/app/views"

  app/controllers/application_controller.rb:93:in `set_currency'


-------------------------------
Request:
-------------------------------

  * URL        : http://127.0.0.1:3001/apple-touch-icon.png
  * HTTP Method: GET
  * IP address : 127.0.0.1
  * Parameters : {"controller"=>"home", "action"=>"index", "foodcoop"=>"apple-touch-icon", "format"=>"png"}
  * Timestamp  : 2021-09-15 17:28:57 UTC
  * Server : *********
    * Rails root : /home/foodsoft/foodsoft
  * Process: 7586
```

**Comment by carchrae** [comment]
submitted a PR - i haven't tested if this resolves it (i don't have an ios device), but i think it should.  

and yes, perhaps a committee should be formed to choose the image, but i went rouge!  :D  

![image](https://user-images.githubusercontent.com/959825/133489683-897f6f8f-7ab0-497f-bd6c-a63d0037b203.png)
