### ISSUE TITLE
Allow editing recurring task groups

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodsoft#152]
When a recurring task is edited, a copy is made to a non-recurring task so that the exception can be edited. It would be useful to be able to edit the recurring task properties as well.

See also #142 and #151.

**Comment by wvengen** [comment]
@robwa would you like to look at this issue? I've tried to give it a shot, but I'm not really sure how to do this properly.

**Comment by robwa** [comment]
I will try to produce some code. It will take some days or maybe even weeks, but I won't forget it.

**Comment by wvengen** [comment]
Thank you!
And I'll have patience - whether in time for the 4.4 release I'd like to do within some weeks, or not.

**Comment by robwa** [comment]
Please have a look at the feature branch. For me it works.

'Responsible Users' and 'Done?' are not updated as it wouldn't make sense to me.

Maybe we should adjust user interface a little bit (messages, button label)?

**Comment by wvengen** [comment]
Thanks! I agree that users and done don't need to be updated. Perhaps done tasks should not be touched?

I'm pondering whether it would be clearer to change all repeating tasks *after* the task edited (similar to existing calendar applications). What do you think?

**Comment by robwa** [comment]
> Perhaps done tasks should not be touched?

As far as I remember tasks are excluded from the group when marked as *done* (as they are at any modification).

> I'm pondering whether it would be clearer to change all repeating tasks after the task edited (similar to existing calendar applications).

I'm not familiar with existing applications. What would be the workflow for the user? Could you outline it?

**Comment by wvengen** [comment]
> As far as I remember tasks are excluded from the group when marked as done (as they are at any modification).

Ah, of course :)

> What would be the workflow for the user?

Looking at some apps, I find that the most important options are "change only this event" and "change all events in the series" (Android calendar app's wording), with "Change this and all future events" as well for some apps. I guess current functionality is perfect!

**Comment by wvengen** [comment]
In-line with the current UI, we could add a button "Edit task and subsequent".
![foodsoft_-_show_task_-_2015-05-08_13 19 06](https://cloud.githubusercontent.com/assets/503804/7535394/e55fe6d2-f584-11e4-838e-2fd733bc0c01.png)

But it becomes a bit crowded.
![foodsoft_-_show_task_-_2015-05-08_13 31 50](https://cloud.githubusercontent.com/assets/503804/7535533/9a368f42-f586-11e4-9d6d-61dad01ae787.png)

**Comment by wvengen** [comment]
Perhaps
![foodsoft_-_show_task_-_2015-05-08_13 34 44](https://cloud.githubusercontent.com/assets/503804/7535570/039067ce-f587-11e4-8592-48ab1dce5e57.png)

The delete recurring confirmation dialog gives explanation, and we could use a flash message in the edit and edit recurring screen to explain what happens.

**Comment by wvengen** [comment]
(looking twice, I'd prefer the recurring icon _before_ the text)

**Comment by wvengen** [comment]
I've been so free as to commit this in a00e7c94bece8d85da2c786f40a7196517f3f5d0
Do you like the change?

**Comment by robwa** [comment]
Thank you! I really like the changes.

**Comment by wvengen** [comment]
Thanks!
