### ISSUE TITLE
RSS feed for wiki updates

### ISSUE THREAD

**Issue by gettingfooddone** [foodcoops/foodsoft#223]
Gibt es eine (einfache) Möglichkeit, die Wikiinhalte als rss/atom/feed zu extrahieren bzw. dem Browser anzubieten?

Warum ich denke, dass es hilfreich wäre: Wir haben ja die ein oder andere Diskussion bei uns per Wiki. Da wünschte ich mir häufig a) überhaupt von Änderungen mitzubekommen und b) dann auch die Unterschiede seit der letzten Änderung zu erkennen. Deshalb stelle ich mir vor, dass die FoodSoft bei jeder Änderung den kompletten Artikel als ganzes per rss parst. Dann könnte ich mit diff mir selbst die Änderungen anschauen und bekomme z.B. per Emailclient oder Webbrowser mit, dass sich etwas geändert hat.

Ist ne Lösung für Technikaffine, ich weiß, aber ich schätze, jede Änderung farblich hervorzuheben, dürfte codetechnisch aufwendiger sein als "einfach nur" einen irgendwo herumliegenden fertigen rss-parser ins wiki einzuarbeiten. Oder sehe ich das falsch?

Besten Gruß

**Comment by gettingfooddone** [comment]
Hi.

I'd like to reopen this (or should it be a new issue?). Thing is, since a few weeks my mail client doesn't recieve a valid feed anylonger. Last entry i got is from 19.11.15. It seams to be version 4.4.1 (it's hosted on apps.foodcoops.net).

How can I be of help to fixing this? Cheers.

**Comment by wvengen** [comment]
The feed from app.foodcoops.net's demo is [this rss feed](https://app.foodcoops.net/demo/pages/all.rss?token=BAhbB0kiCWRlbW8GOgZFVEkiDXdpa2k6YWxsBjsAVA%3D%3D--ac0eb18d9b8d7544b75d0e1047698ce2fedb7cdd).

There appear to be some problems, according to [this feed validator](http://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fapp.foodcoops.net%2Fdemo%2Fpages%2Fall.rss%3Ftoken%3DBAhbB0kiCWRlbW8GOgZFVEkiDXdpa2k6YWxsBjsAVA%253D%253D--ac0eb18d9b8d7544b75d0e1047698ce2fedb7cdd). Is that your problem, or do you experience something else?

You could test your rss feed for validity, and see what needs to be changed for it to work in your rss reader, as a first step.

**Comment by wvengen** [comment]
And please feel free to open a new issue if it remains a problem. (Please include all revelant details, and mention this issue for reference.)
