### ISSUE TITLE
Improve StockTaking usability

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#236]
Currently, the `StockTaking` form is quite puristic. I would like to discuss some improvements I have in mind. What I currently miss:
1. There are too few information about the `StockArticle` (prices, supplier, category).
2. It is not possible to edit, create, delete... `StockArticles`.
3. One has to calculate the difference for the `StockChange` manually, i.e., to get from `quantity_available=5` to `quantity_available=7` one has to enter `2`.
4. Once saved, it is not possible to edit the `StockChanges` of a `StockTaking`.
5. It is hard to tell if all `StockArticle` quantities have been checked. Imagine you want to perform an inventory for the whole stockit, then you need to know which `StockArticles` have already been addressed by a `StockTaking`.

You find some ideas implemented in [foodcoop-rostock/foodsoft feature-customize-stock-takings](https://github.com/foodcoop-rostock/foodsoft/tree/feature-customize-stock-takings). I would be happy about some comments how to improve it.

Should we target an improvement step-by-step here or does it make sense to make an overall plan first?

**Comment by wvengen** [comment]
Hmmm it looks like some things have changed here, has it?

**Comment by JuliusR** [comment]
Yes, this issue refers to an extremely old version of the StockTaking form.

Let us close this issue.
