### ISSUE TITLE
Tag for release 4.3.0 should be 4.3.0 instead of 3.4.0

### ISSUE THREAD

**Issue by marcopenhacking** [foodcoops/foodsoft#335]
Probably a typo on New Year's Eve.

https://github.com/foodcoops/foodsoft/commit/80cb806122f3607a4f0eb50f5e99bb4a72fb7b6e

Maybe the tag can be corrected. Otherwise it should be not problem if it's known that this is the currently latest release.

**Comment by wvengen** [comment]
Oops, thanks!
