### ISSUE TITLE
No validation on missing unit_quantity when uploading articles

### ISSUE THREAD

**Issue by bennibu** [foodcoops/foodsoft#339]
I haven't confirmed it yet, but a few users describing following problem. When they upload articles via the foodsoft csv file format and they not setting the unit_quantity there are no warnings, but the articles are stored in database with a unit_quantity = 0. This causes an error later on, when they try to open an order with these articles selected.

If thats correct, a quick workaround maybe a default value for unit_quantity of 1, set in database migration.

**Comment by wvengen** [comment]
Thanks for reporting. unit_quantity does have a validation on being present and greater than zero. The upload form should catch this, but I'll have a look to see if I can reproduce it.

I did see a problem once with sharedlists, where validation was different from Foodsoft, leading to problems. Is this what you're seeing?

**Comment by bennibu** [comment]
Maybe its related to shared list. This is also possible. But in the last
case, the user didn't use the sharedlist concept, so please check the
csv upload workflow too. Thanks!

Am 14.01.2015 um 17:54 schrieb wvengen:
> Thanks for reporting. unit_quantity does have a validation on being
> present and greater than zero. The upload form should catch this, but
> I'll have a look to see if I can reproduce it.
> 
> I did see a problem once with sharedlists, where validation was
> different from Foodsoft, leading to problems. Is this what you're seeing?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/foodcoops/foodsoft/issues/339#issuecomment-69948917>.
> 

-- 
pgp Schlüssel-ID: 0x3B2EE0A4
Fingerabdruck: 805F 73B1 9F45 4122 2FE6 ED75 0786 8427 3B2E E0A4

**Comment by wvengen** [comment]
Ok, I tried it. When unit_quantity is blank in the Foodsoft CSV, import fails with the error _"A problem has occured: Unit quantity can't be blank, Unit quantity is not a number ... in line 3"_.
![warning](https://cloud.githubusercontent.com/assets/503804/5747190/7952af6c-9c36-11e4-9277-bdb9d52d247d.png)

When unit_quantity is not blank, but in the form after import the unit_quantity is made empty, submitting the form gives an error as well.
![formerror](https://cloud.githubusercontent.com/assets/503804/5747209/aafa2310-9c36-11e4-8581-673476a01273.png)

What version of Foodsoft are you using? Can you reproduce it with the latest one?

**Comment by bennibu** [comment]
thanks for looking into it. I will ask the user for its csl files.

**Comment by wvengen** [comment]
This has been open for quite a while without a clear framing of the problem, I'd like to close it now. If this is still a problem, please feel free to reopen.
