### ISSUE TITLE
Update profile fails if user has no ordergroup

### ISSUE THREAD

**Issue by bennibu** [foodcoops/foodsoft#340]
Version: 4.3.0

Url: https://app.foodcoops.net/stadtkern/home/update_profile (PATCH)
Backtrace:
    param is missing or the value is empty: ordergroup
    app/controllers/home_controller.rb:77:in `ordergroup_params'

**Comment by wvengen** [comment]
Oh no! Thanks for reporting.

**Comment by wvengen** [comment]
Out of curiosity: what is the use for members without an ordergroup?

**Comment by wvengen** [comment]
Fixed in 65c7673a4120538d2b6324ce3a9a592d3509bba1. I'd like to release 4.3.1 for a hotfix. Any other bugs found?
