### ISSUE TITLE
Embed images in the wiki

### ISSUE THREAD

**Issue by Tamriel** [foodcoops/foodsoft#343]

**Comment by wvengen** [comment]
Hi, thanks for your issue. This would indeed a desirable thing to have, especially so with #342. At the moment, Foodsoft doesn't handle file attachments, but [wikicloth](https://github.com/nricciar/wikicloth) does support embedding images, so external ones should be supported already.

**Comment by Tamriel** [comment]
According to wikicloth
    [[https://www.google.de/images/srpr/logo11w.png]]
should display an image.
This does not work in foodsoft 4.3 ?

**Comment by wvengen** [comment]
I needed to look in the wikicloth sourcecode, but you can do `[[Image:https://www.google.de/images/srpr/logo11w.png]]`. I've added it to the [usage notes](https://github.com/foodcoops/foodsoft/wiki/Usage-notes).
