### ISSUE TITLE
www.foodcoop.test

### ISSUE THREAD

**Issue by MikeiLL** [foodcoops/foodsoft#379]
Is www.foodcoop.test where I should be seeing the front end? Is there a particular url that my hosts file needs to point to in order to be able to access it via the browser? Is this something that will only be accessible after deploying to staging?

**Comment by wvengen** [comment]
This is just a default value, which can be changed in the configuration. It does not point to anything. In reality, you would point this to your foodcoop's main website.

**Comment by MikeiLL** [comment]
Is there a separate "front end" somewhere that I'm not seeing in the dev install? What does the "customer/member" see?

**Comment by wvengen** [comment]
No, all can order and some can see and can peform more options, depending on their workgroups and its permissions. The default admin user can do everything.

**Comment by wvengen** [comment]
I hope this answers your question, if not please feel free to reopen the issue.
