### ISSUE TITLE
Foodcoop profit missing

### ISSUE THREAD

**Issue by Tamriel** [foodcoops/foodsoft#381]
When I go to 'finances' -> 'clear orders' and open an order, I get this screen:
![bildschirmfoto 2015-08-26 um 00 12 43](https://cloud.githubusercontent.com/assets/5037153/9481049/6483c0de-4b87-11e5-9767-b22b1dda30ee.png)

We have a price markup / Foodcoop margin enabled and it get's subtracted from the buying price, but the profit at the left is not calculated.

**Comment by wvengen** [comment]
This number is only available when an invoice (Rechnung) is present. The profit is then the amount that came in (Gruppenbetrage) minus the amount payed (from the invoice).

**Comment by Tamriel** [comment]
I'm sorry, we did a mistake when calculating the invoice.
All is well :)

**Comment by wvengen** [comment]
No problem, thanks for mentioning.
