### ISSUE TITLE
first login credentials

### ISSUE THREAD

**Issue by MikeiLL** [foodcoops/foodsoft#384]
Hey man,

Is there a place where the docs explain how to get the login credentials for the first time when initial set-up is complete? Of course one could add an administrator directly in the database. I looked in users, found the admin email and searched the code to find the password; "secret" in four files:

    * `db/migrate/001_create_users.rb`
    * `db/seeds/minimal.seeds.rb`
    * `db/seeds/small.en.seeds.rb`
    * `db/seeds/small.nl.seeds.rb`

Is the one in the migrate file created dynamically? Is the developer supposed to set this somewhere? Please excuse me if I just missed this step in R-ing TFM.

**Comment by wvengen** [comment]
Hi, [SETUP_DEVELOPMENT](https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_DEVELOPMENT.md) explains that you can login with `admin`/`secret` after running the install script. This is part of the database seeding with rake task `db:seed` (which is run as part of the `db:setup` task) which loads the minimal seed.

**Comment by MikeiLL** [comment]
thanks.
