### ISSUE TITLE
relationship between order and invoice

### ISSUE THREAD

**Issue by paroga** [foodcoops/foodsoft#390]
At the moment it is possible to have "n" invoices for an order, but only "1" order per invoice. We have the practical problem that we make weekly orders, but get monthly invoices. Do we need the "n" invoices per order feature, or could we just swap the "1:n" relation?

**Comment by wvengen** [comment]
Hmm good question. I'm curious who is using multiple invoices per order, but it makes sense as well. I think this would be a useful question for the foodsoft-discuss mailing-list.
How would you picture the UI for this?

**Comment by paroga** [comment]
If you do not change the database or "hack" the UI by entering special urls it's not possible to add more than one invoice. So it should be safe to migrate it.

My picture: Keep the "add invoice" button as it is, but on the "new invoice" page i have a list of associated orders. I could edit the list similar to the membership list of groups, but it is only possible to add orders of the corresponding supplier which have not been balanced before and do not have an assigned invoice. Later I'd like to add a "sum of order totals" to have an easy UI for comparing it against the total of the invoice (which should be the same in an ideal world)

**Comment by paroga** [comment]
committed in 460cf1e82cd49335957ef61c8ff073ae7cedc437
