### ISSUE TITLE
Broadcast messages to all users, i.e. send message to user "all"

### ISSUE THREAD

**Issue by gettingfooddone** [foodcoops/foodsoft#393]
Hey,

would it be possible (or maybe even easy) to broadcast a new message to all users in the foodsoft instance? I would like to type "all" (or similar) in the first field of a new message and than it would be send to every single user. Maybe "all" could just be expanded to all the user names known or such?

Edit: As far as i get it this feature would make foodsoft messages replace a mailing list (ml). In addition to ml one would have the option to not receive every mail but to read them online within foodsoft at will.

Cheers and thanks a bunch for all your nifty work so far!

**Comment by wvengen** [comment]
There is a checkbox "send to all members". Is that what you mean?

**Comment by gettingfooddone** [comment]
thanks for your quick reply.

In my form i only see a checkbox for "private" (i use a german version, so maybe it's not the exact english term) which, i suppose, only hides my message from the messages overview page /messages. Other checkboxes i cannot see on /messages/new.

Some users may opt for foodsoft to send messages by email to them, i.e. notify. What i'm looking for is to actually send my message to everyone, i.e. notify all. Sorry for my poor description.

**Comment by wvengen** [comment]
All the way on top there is _An alle Mitglieder schicken_:

![foodsoft_-_neue_nachricht_-_2015-12-02_00 15 24](https://cloud.githubusercontent.com/assets/503804/11517450/cd02438e-9889-11e5-884e-bf3e011b8a70.png)

**Comment by gettingfooddone** [comment]
That seams to be what i ment but i'm sorry, i don't have that (see pic). Is it an option in the config somewhere or what could be the reason?

![messages-new](https://cloud.githubusercontent.com/assets/4964062/11517557/85d613c2-988a-11e5-96dd-d385ceac5df2.png)

**Comment by wvengen** [comment]
Ah, that means you are using mailing-lists for communication between all members. Remove the mailing-list email addresses in the configuration, and this message will be replaced by the checkbox in my screenshot.

**Comment by gettingfooddone** [comment]
thanks, @wvengen, for that hint and sorry for asking in the first place. 

From my standpoint it's closed (before it was open ;) )

I would have marked this issue closed myself but couldn't find an option.

**Comment by wvengen** [comment]
No problem, glad you asked! Documentation could be improved on this :)
