### ISSUE TITLE
SQLException: duplicate column name when migrating 

### ISSUE THREAD

**Issue by Kristiyan96** [foodcoops/foodsoft#425]
It is highly probable to be my fault but when doing the initial migrate I get this:
SQLite3::SQLException: duplicate column name: salt: ALTER TABLE "messages" ADD "salt" varchar
I migrate after step 5) in the guideline for running the app locally.

**Comment by wvengen** [comment]
Oops, this is a bug in the schema, the version wasn't updated in the last commit. Thanks for reporting this!

**Comment by wvengen** [comment]
If you're able to drop the database and re-create it, that'll work after the fix. If you have data to save, let me know, and I can give you some SQL to mark the migration as done in the database.
