### ISSUE TITLE
Granting specific access rights to new users 

### ISSUE THREAD

**Issue by simnh** [foodcoops/foodsoft#426]
Hi, I found foodsoft today and set it up locally. It looks like a great project! 

Playing around, I tried to create new users via the browser but I was not able to grant any specific access rights to them. I could not figure out how to do that by manipulating the sqlite3-database as well. What do I miss here? 

Help would be great! 
Simon

**Comment by simnh** [comment]
Ok found it. I had to create a workgroup with specific rights and then add the user to this group...

**Comment by wvengen** [comment]
Indeed, glad you found it. Thanks for documenting the outcome :)
