### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by ahimor** [foodcoops/foodsoft#427]
Is there a way to see who ordered what on foodsoft ?

i want each user to see what he ordered and how much to pay....i guess i didnt understant how the system works.... help please

thanks

**Comment by wvengen** [comment]
Hi, in _Orders_ > _My orders_ you can see what you ordered in the past.
An admin can go to _Orders_ > _Manage orders_ and for each order press the _Show_ button, where you can see what was ordered in total, or using the buttons _Sorted in groups_ and _Sorted in articles_ you can see what member ordered what. There's also the option to download PDFs with this information.
Does this help?

**Comment by ahimor** [comment]
yes very much thank you !
:)
i heard there is an amsterdam fork of foodsoft...
is it also free & open source?
do you know the address ?

**Comment by wvengen** [comment]
@ahimor :+1:
The fork is at [foodcoop-adam/foodsoft](https://github.com/foodcoop-adam/foodsoft). It has some extra features and changes, but it's more likely to break (though I try not to), and the aim is to merge the functionality into upstream (this repository).

**Comment by wvengen** [comment]
You can look a demo of the foodcoop-adam fork (currently) at https://order.foodcoopamsterdam.nl/foodsoft/demo (same admin login as foodcoops.net demo), if you'd like to have a look.

**Comment by ahimor** [comment]
actualy i didnt get to the part where it says what a member ordered.....
when i go as a user to my orders it show only what the group ordered....
maybe the settings are not right on the demo ?

**Comment by wvengen** [comment]
Foodsoft members order in _ordergroups_, which is usually a household. Members of the household have their common order. Some foodcoops have only one member per ordergroup, other foodcoops may consist mainly of ordergroups with multiple people.

Ordergroups are different from _workgroups_, which exist to give people permission to certain areas.

**Comment by ahimor** [comment]
is this an answer for "splitting" orders ?

**Comment by wvengen** [comment]
With "splitting" orders is usually meant that different people can fill a box (like both getting 6 of a box of 12 pieces). Ordergroups are different, they are equivalent to a household, where e.g. partners can manage their household's order together while still having different logins (e.g. for tasks).

**Comment by ahimor** [comment]
i have a server, not on my pc....
if i take the files you mentioned (https://github.com/foodcoop-adam/foodsoft
)
and copy the to a folder on the server it would work ?

sorry for asking so many questions...... our group is getting bigger and we
need this system.....
but nobody understands how to put it....
if you can help me it would be world changing !!!!
thanks for your time

**Comment by wvengen** [comment]
Did you find this wiki page already? https://github.com/foodcoops/foodsoft/wiki/For-foodcoops
Foodsoft is a standard Ruby on Rails app, and needs a little expertise to get it going. If you're ok with that, [doc/SETUP_DEVELOPMENT.md](https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_DEVELOPMENT.md) would be a good start, when that works you'd move to production as explained in the wiki page.
If you'd just like to _use_ Foodsoft, I'd ask one of us to participate in the Dutch or German installs (see wiki page). Or if you want to run your own, you can run a ready-made [virtual machine](https://www.turnkeylinux.org/foodsoft) (though it's not always the latest version and I have no experience with upgrading in this case).

**Comment by ahimor** [comment]
you are saying you can help me with a server with an installed "amsterdam
foodsoft" ?
if there is anybody that can help us with that it would be wonderful !

**Comment by wvengen** [comment]
Yep. I'll be happy to create a setup for you, somewhere this week (if it works out). What is the foodcoop name you'd like to use (will be part of url)?
And after some weeks/months, when you're still using it, I'll ask if you would be able to share in the costs of renting the server (couple of euros per month per cooperative).
There is also a possibility for members to do online payments, if you're interested.

Let's discuss this over email (since this will also be about the creation of an account) - info at the domain voedselcollectief dot org will do.

**Comment by ahimor** [comment]
that would be wonderful :)
we are a non profit bussiness but we get donations and are getting bigger
so payment wont be a problem :)

it is called "Coopnoded"
is it possible to setup the amsterdam version of foodsoft ?

let me know if you need anything..... thanks again !

**Comment by wvengen** [comment]
@ahimor No problem. Please mail me privately so I can contact you about the account.

**Comment by ahimor** [comment]
please explain what you mean....

**Comment by wvengen** [comment]
please contact me by email as mentioned in [this post](https://github.com/foodcoops/foodsoft/issues/427#issuecomment-217793393) (and [this](https://en.wikipedia.org/wiki/Address_munging#Examples) may help if you're confused)

**Comment by ahimor** [comment]
i have got a lot to learn , thank you wvengen ...
i tried all methods on wiki.... it doesnt send the mail.....

sorry for not returning a mail yesturday it was late and my wife wanted to sleep,
we live in a tent on the galilee sea....
so we walk a mile from there to get internet....
you are mostly  welcome to come whenever you want :)
it would be a pleasure.

so what is our next step ?

**Comment by wvengen** [comment]
Ah, I see, wow :) Supposing you have an email address, please send me a regular mail (not public Github issue) to info@voedselcollectief.org

**Comment by ahimor** [comment]
did i do anything wrong please tell me ?

**Comment by wvengen** [comment]
(@ahimor please see email)
