### ISSUE TITLE
Timezone issue, order ending

### ISSUE THREAD

**Issue by Schaussi** [foodcoops/foodsoft#436]
Hi,
I have the current Foodsoft Turnkeylinux ISO installed.
As far as I could find out, the system should close orders automatically at the ending time. Is this correct?
If yes, I think there could be a timezone issue, e.g. with the foodsoft background process. We have to close the orders manually.

Settings:
- GMT+1 (Vienna) in foodsoft admin settings
- /etc/timezone: Europe/Vienna

Shell "date" command, foodsoft web interface, PHP "date()" and MySQL "curtime()" all show the correct local time.
The MySQL "orders" table itself, e.g. "ends" column, contains DateTime values which are 2 hours earlier before the local time.

Please give me some information what we could do to close orders automatically at the local "end time".
Thank you!

**Comment by wvengen** [comment]
Hi, thanks for your bug report.
The system does not close the order automatically. A manual step is needed anyways to place the order with the supplier (or whatever the cooperative chooses to do), so it doesn't really add value to do that automatically. Or are we missing something in that line of thought?

**Comment by Schaussi** [comment]
You are right, it is not a big problem, the orderer would need about 1 less mouse click.
I just thought the background process might already do this and it's only a time issue in our case.
In my opinion, users could get confused if the order is listed as active, but time is actually over.
Nevermind, maybe I will start a cronjob to fix this for us.
The foodsoft system in general is great, thank you.

**Comment by wvengen** [comment]
I agree that this could be clearer. Cronjob is not a bad idea, and would also allow opening an order at a specified time (e.g. to setup orders for the following months - would need some UI improvements as well though).
In foodsoft-shop, I've added something like `was expected to be closed yesterday` when times are past.

**Comment by wvengen** [comment]
Please feel free to open a new issue for the cronjob if you think that would be an improvement.
