### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Schaussi** [foodcoops/foodsoft#441]
Hi,
I am using the current Turnkeylinux ISO setup, installed on a MS Hyper-V VM.
When the system is up running for more than about 6 hours, the system gets extremely slow and has to be rebooted.
First, I added the grub parameter "nohz=off". It helps a bit, but does not solve it.
"Top" command does not really show a certain fault process, but a high load.
![1](https://cloud.githubusercontent.com/assets/4758559/16559144/1901a0c6-41eb-11e6-9717-2391a97a98ad.JPG)
When I try to reboot, "Foodsoft background process" takes a very long time to finish.
![2](https://cloud.githubusercontent.com/assets/4758559/16559148/1e1db3b0-41eb-11e6-8c2b-4d034f859dab.JPG)
Could it be helpful to use a backport kernel?
Maybe you could give me some hints to solve this issue.
Please let me know if you need further details.
Thank you

**Comment by wvengen** [comment]
Thanks for filing the issue. That looks like it's pretty inconvenient!
It looks like the background worker is using a lot of cpu (which is strange, because it really isn't doing that much). Can you view the complete command-line for the processes (`ps auxww | grep ruby`)? That would probably show it's the background job, and how it is run.

Also `strace` on the affected process can be useful to see what interaction with the system it might have (e.g. trying to read files or so).

**Comment by Schaussi** [comment]
Unfortunately, the issue is hardly reproducible. At the moment, the system has been running for 1d 5h without any strange loads. The daily usage is always quite the same: Order generated at about 05:00 am, users order their articles, order closed at 07:25, group PDF generated, order received at about 09:30.
Does the foodsoft background process have any separate log file where to find more information?
Thank you

**Comment by wvengen** [comment]
There are log files in `/var/www/foodsoft/log` - there's one for the worker as well (though it might also log something to `production.log`, not entirely sure).

Would it be a memory issue? e.g. `free -m`

**Comment by Schaussi** [comment]
First I thought Hyper-V dynamic memory allocation could be the problem, but it was not the cause. I set it to static anyway.
With new kernel 4.6, it runs much better, e.g. load is nearly always 0.00, so I think this issue is solved. Thank you for your help.

In case anyone has the same issue:
`echo "#Backports" >> /etc/apt/sources.list && echo deb http://ftp.de.debian.org/debian/ jessie-backports main >> /etc/apt/sources.list
apt-get update
apt-get -t jessie-backports install linux-image-amd64
reboot
#test with uname -r
`

**Comment by wvengen** [comment]
Thanks for reporting back, and glad you've found a solution.
