### ISSUE TITLE
Docker image for production

### ISSUE THREAD

**Issue by paroga** [foodcoops/foodsoft#449]
The current Docker image seams ok for development, but it does not really work in production without some work.
What do you think about providing a Docker image for production with all releases as tags on Docker hub?
For that I'd like to (re)move the current Docker files and create new ones for production (including some scripts for nice bootstrapping). If you look at the period the Docker stuff did not work lately, I see no real demand in keeping the current stuff.
Background: We are now in the final phase of setting up Austrian Foodsoft Hosting and choose Docker as basis for our infrastructure. Since I do not want to maintain the Docker files in my own repository, it would be great if the official version version does already everything out-of-the-box. ;-)

**Comment by wvengen** [comment]
Sounds like a great idea :+1:

**Comment by simon04** [comment]
For later reference: @paroga adapted the Dockerfile file, https://github.com/foodcoopsat/foodsoft/commit/e0b1433f1e0290b0637385a903069eb68122d401. The build is running on Docker Hub: https://hub.docker.com/r/foodcoopsat/foodsoft/

**Comment by paroga** [comment]
Closed with PR #482
