### ISSUE TITLE
missing translation en.admin.confirm breaks delete button

### ISSUE THREAD

**Issue by carchrae** [foodcoops/foodsoft#467]
there are two issues here.  (v4.5.99)

the simple one is that there is a translation missing:  `en.admin.confirm`

a slightly more complicated issue is how the error is displayed.  the problem is using a span instead of a simple string.  this means that the html shown is malformed.  in this example, the translation goes inside a `data-confirm` tag, so when a `span` is inserted, with `"`s then it breaks the html.  

```html
<a data-confirm="<span class=" translation_missing"="" title="translation missing: en.admin.confirm">Confirm" class="btn btn-mini btn-danger" rel="nofollow" data-method="delete" href="/f/admin/messagegroups/5"&gt;Delete</a>
```

![image](https://cloud.githubusercontent.com/assets/959825/24152223/424cbf26-0e08-11e7-9d6c-83758e91346c.png)

**Comment by wvengen** [comment]
Ouch. Is this happening on a production system as well?

**Comment by carchrae** [comment]
well, nearly production.  :)  

it is running on heroku, so i am not sure if that caused any problems.  i've never used locale app before.  i haven't noticed any other translation missing warnings.

**Comment by wvengen** [comment]
I've seen this in the development environment, but not otherwise. In any case, thanks for reporting.

**Comment by carchrae** [comment]
hmm.  i should check to see what configuration my heroku instance is using, perhaps that is the problem.  i suppose in development, the warnings would appear?  in production, it is more subtle?

**Comment by wvengen** [comment]
That's what I have seen, yes. Set the environment variable `RAILS_ENV=production`.

**Comment by carchrae** [comment]
yes, that variable was set (heroku does that by default for rails apps).  i added the missing translation to the locale and it fixed it: https://github.com/carchrae/foodsoft/commit/6ba04df281b3136df4d7b938e1ac2ec879a8dcd1

i'll make a branch and a PR if you like.  but it is such a trivial change, might not be worth it all that effort.

**Comment by carchrae** [comment]
ah well, i needed to remind myself of how to cherry pick a commit.  :)
