### ISSUE TITLE
Docker build fails due to capybara-webkit

### ISSUE THREAD

**Issue by simon04** [foodcoops/foodsoft#480]
The Docker build fails due to the `capybara-webkit` gem added in b857b1081476108f0148c3646a9f1020a9e2e7b1. This affects a local build (`docker build .`) as well as the automated one on Docker Hub: https://hub.docker.com/r/foodcoops/foodsoft/builds/btxrfowoysusjwr5qq8kcsz/

**Comment by wvengen** [comment]
Thanks for finding out, this was indeed missed! I suppose we'd need to install an extra package?

**Comment by wvengen** [comment]
This being reworked now, Docker is being setup for production use. If you're interested in using Docker for development, please open a new issue, there may be interest to pick it up.
