### ISSUE TITLE
docker-compose fails with "repository foodsoft_app not found"

### ISSUE THREAD

**Issue by simon04** [foodcoops/foodsoft#481]
Following https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_DOCKER.md, I get:
```
$ docker-compose run app rake foodsoft:setup_development
Pulling bundle (foodsoft_app:latest)...
ERROR: repository foodsoft_app not found: does not exist or no pull access
```

Related: 0bdeaa1570e26cbdafec203d15bd344a2e802189

----

For testing, I applied the following modifications:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 4b1b0968..5aa9994d 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,14 +1,6 @@
-bundle:
-  image: foodsoft_app
-  command: /bin/true
-  volumes:
-    - /home/app/bundle
-
 app: &app
   build: .
   command: bundle exec rails server --binding 0.0.0.0
-  volumes_from:
-    - bundle
   volumes:
     - .:/home/app/src
   ports:
```

**Comment by wvengen** [comment]
Hi Simon, thanks for opening the issue. The default Docker setup is indeed broken, right now. Great to have a workaround/solution. I hear that people are reworking the Docker deployment.

**Comment by wvengen** [comment]
This has been reworked in #523 and should not happen anymore. Feel free to re-open when you encounter this specific issue still.
