### ISSUE TITLE
Switch license to AGPL

### ISSUE THREAD

**Issue by paroga** [foodcoops/foodsoft#496]
GPL does not require hosters to publish their changes, but AGPL does.

**Comment by wvengen** [comment]
That would be a good move, in my opinion.
Is it compatible with other licenses of gems and such we use?
I'm curious to hear other's opinions on this.

**Comment by wvengen** [comment]
Great step! What are the licenses of third-party components we include (e.g. in vendor)? Are they compatible? (e.g. LGPL [is not](https://opensource.stackexchange.com/questions/5637/use-lgpl-code-in-an-agpl-project) without measures)

Also, I would put this through the developers mailing-list, just to make sure everbody is on board. Not everyone may be watching Github.

**Comment by wvengen** [comment]
Also, I would not want the license to fence off people wanting to use Foodsoft, as long as it's within our realm of values.
What is our position if, for example, a foodcoop changes the source code, and hosts the service for their own use without making it open source (not or not yet). What would we want? Is is allowed by the AGPL? Do we want people to contact us and allow the developer team to provide (temporary) exceptions?
I think it would be good to have some clarity on these questions before proceeding.

**Comment by paroga** [comment]
I want that if somebody changes something in the source code he/she MUST provide the changes. I don't want that people "improve" the code only for their own foodcoop. That's not the idea behind open source. I think we all put enough time into the code, that it's a reasonable requirement that other people must at least share their code changes. If that fences people off, then they should not be allowed to use foodcoop. An unmodified installation (which is the 99% use case) is still possible without any further restrictions. I do not see any reason for (temporary) exceptions. I want that other people have to share their code changes if they use a modified version of foodsoft. That's the base idea of the GPL. AGPL just adopts that idea for network services.
So I think our position should be exactly what is written in the AGPL.

**Comment by wvengen** [comment]
I agree with the spirit of your last comment.
Nevertheless, I might feel uneasy even just running Foodsoft. Does changing the configuration file (`app_config.yml`) constitute a source change? The environment settings? Extra css? Tweaks in the views?
I think we could agree to a certain boundary, but as a user I would feel a little uneasy about this if I knew a little about licensing. We could make this a bit clearer by giving examples of things that we consider ok, and things that we don't consider ok. 

The GPL is clear in that respect: if you redistribute anything, make sure to also redistribute the source.
With the AGPL I think some extra clarification is needed.

**Comment by paroga** [comment]
I agree that we should clarify the situation with the configuration files (app config, database config and environments). IMHO they should become public domain.
Extra CSS (not set via FoodsoftConfig) and changes in the views are changes to the source code, which should be made public.
Creating a fork on github and pushing a commit is only a work of a few minutes and there is no excuse for not doing this - even for a typo.

**Comment by wvengen** [comment]
What about something like this:
> Foodsoft is licensed under the [AGPL](https://www.gnu.org/licenses/agpl-3.0.html) license (version 3 or later). Practically this means that you are free to use, adapt and redistribute the software, as long as you publish any changes you make to the code. 
>
> For private use, there are no restrictions, but if you give others access to Foodsoft (like running it open to the internet), you must also share your changes under the same license. This can be as easy as [forking](https://github.com/foodcoops/foodsoft/fork) it on Github.
>
> To make it a little easier, configuration files are exempt, so you can just install and configure Foodsoft without having to publish your changes. These files are marked as _public domain_ in the file header.
> 
> If you have any remaining questions, please [open an issue](https://github.com/foodcoops/foodsoft/issues/new) or contact the [mailing list](http://foodsoft.51229.x6.nabble.com/foodsoft-discuss-f5.html).

I can see people wanting to, for example, change the cookie path or adapt the exception notifications beyond what's possible in the app config. I would be open to allowing that.

(I did come across people who were experimenting with installing their own Foodsoft instance, new to Ruby, and for whom publishing the source code could have been quite a step, mentally. I would like to make it as smooth as possible for them as well.)

**Comment by paroga** [comment]
> For private use, there are no restrictions, but if you give others access to Foodsoft (like running it open to the internet), you must also share your changes under the same license. This can be as easy as forking it on Github.

I see no need for this paragraph. If you use only local on your own machine (for testing) there is no conflict with the AGPL. IMHO adding some exceptions to a license when you're not a lawyer is not a good idea.

I agree that publishing the first change to an open source project is such a step, but I want that other people MUST publish their changes. ATM the GPL is useless in that field. If people do not agree with the license they are always free to just use another software.

**Comment by wvengen** [comment]
This paragraph is meant for people who are somewhat new to (open source) licensing. You and me know that there is no conflict with the (A)GPL for local use, but many people I speak don't realize that there is a difference until it is explained. Because we mention a restriction, this helps unknowledgable people to know that they can freely use it on their computer, and specifically mentions that exposing it on the internet requires redistribution of changes. That's why I'd like to include the paragraph.

**Comment by wvengen** [comment]
This paragraph is meant for people who are somewhat new to (open source) licensing. You and me know that there is no conflict with the (A)GPL for local use, but many people I speak don't realize that there is a difference until it is explained. Because we mention a restriction, this helps unknowledgable people to know that they can freely use it on their computer, and specifically mentions that exposing it on the internet requires redistribution of changes. That's why I'd like to include the paragraph.

I'm very happy with the AGPL change overall, great idea :+1:

**Comment by paroga** [comment]
Maybe we find a better wording, so it's clear that the paragraph is only a short explanation of the AGPL and not part of any licensing.

**Comment by joh-klein** [comment]
Wouldn't part of the solution be, to not include config files in the source code? Or only a "app_config.yml.template" which users would have to rename an thus it is not part of the source anymore …

**Comment by paroga** [comment]
not really, since the environment files (e.g. `production.rb`) are required

**Comment by wvengen** [comment]
Besides, when making a copy the file still has the same license, so the template needs to have a public domain license anyway (IANAL). I'd be happy to release these config files in the public domain.

**Comment by wvengen** [comment]
To give the developers on the mailing list some time to respond, I've [posted](http://foodsoft.51229.x6.nabble.com/Proposal-for-license-change-to-AGPL-please-respond-before-10-Nov-if-you-care-td1489.html) the current proposal.

**Comment by wvengen** [comment]
If there are no objections, I'd like to release Foodsoft 4.6 with the AGPL on the 10th of November.
