### ISSUE TITLE
Help for setup

### ISSUE THREAD

**Issue by Tamriel** [foodcoops/foodsoft#534]
I succesfully followed the guide [SETUP_DEVELOPMENT.md](https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_DEVELOPMENT.md) for foodsoft v4.6.0.
Now I encounter the following problems:
1. For each access with a web browser the console prints `Error during failsafe response: No config for this environment (f) available!`. I put the full exception in this [gist](https://gist.github.com/Tamriel/09a44c31428ce89179ea50df10dc1559).
2. The SSL certificate somehow doesn't work.
3. The console of the web browser prints `Failed to load resource: the server responded with a status of 500 (Internal Server Error) (application.js)`. Therefore the user interface does not look and work like intended. This error may be due to the not-working SSL certificate.

**Comment by wvengen** [comment]
Thanks for reporting, this would indeed be a bug. It looks related to the app configuration file. Is `config/app_config.yml` present?

**Comment by Tamriel** [comment]
Yes, it is.

**Comment by wvengen** [comment]
Thanks for sharing, and that explains it: the indentation is off. Everything between `default` and `development` needs to be indented (e.g. by a tab), just like the original file is.

**Comment by Tamriel** [comment]
The file was created by the rake script. The file `app_config.yml.SAMPLE` looks the same.

**Comment by wvengen** [comment]
That is strange! The instructions would bring you [this config file](https://github.com/foodcoops/foodsoft/blob/master/config/app_config.yml.SAMPLE), which has indentation. (And if you're using docker, that file is also in there.)
Are you sure this file hasn't been changed (`git status`)? What platform are you using?

**Comment by Tamriel** [comment]
I think your linked config file and my gist are the same.
My file is indented, isn't it?

**Comment by wvengen** [comment]
Sorry, that was a rendering issue (if you don't wait long enough for all CSS to load, the file will appear unindented; the raw version shows indentation).
Just to be sure, you did not set the environment variable `FOODSOFT_APP_CONFIG`, right?

**Comment by Tamriel** [comment]
Yes, I did not.
I just did `rake foodsoft:setup_development`.

**Comment by wvengen** [comment]
It's a bit of a mystery to me. I'll try to find some time to reproduce this from scratch (or if anyone is passing by, feel free to try and report back).

**Comment by Tamriel** [comment]
I forgot to import my SSL certificate, sorry.
The third problem still exists, I described it in a seperate [ticket](https://github.com/foodcoops/foodsoft/issues/535).

**Comment by wvengen** [comment]
Thanks for reporting back.
