### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by Tamriel** [foodcoops/foodsoft#535]
I succesfully followed the guide [SETUP_DEVELOPMENT.md](https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_DEVELOPMENT.md) for foodsoft v4.6.0.
However, I installed the gems with `bundle install --without test`, because it is impossible to get Qt with my webhoster. Qt is needed for capybara-webkit.

When accessing the foodsoft, the console of the web browser prints:  
```
Failed to load resource: the server responded with a status of 404 (Not Found) application.css
Failed to load resource: the server responded with a status of 404 (Not Found) application.js
Uncaught ReferenceError: I18n is not defined at login:75
Uncaught ReferenceError: $ is not defined at login:80
```
Therefore the user interface does not look and work like intended.

**Comment by Tamriel** [comment]
I tried the procedure on my local computer. It works fine, even without the gems from `test`.
When I installed the gems on my webhoster, I had a problem with ruby-filemagic. I solved it with the two commands `brew install libmagic` and `bundle config build.ruby-filemagic --with-magic-include=~/.linuxbrew/Cellar/libmagic/5.32/include --with-magic-lib=~/.linuxbrew/Cellar/libmagic/5.32/lib/`.
Any ideas?

**Comment by wvengen** [comment]
Hmm, the assets aren't found. Are you running the development environment (default)?
And are you using a suburi, or running Foodsoft at the domain root (like https://example.com/ instead of https://example.com/foodsoft/) ?

**Comment by Tamriel** [comment]
I am running the default environment.
I use https://foodsoft.example.com, whose `.htaccess`-file contains
```
RewriteEngine On
RewriteRule (.*) http://localhost:62407/$1 [P]
```
Then I start Foodsoft with `bundle exec rails server -p 62407`.

**Comment by wvengen** [comment]
That's odd. Does the url of the js and css in the html seem correct? What does the rails console output say when you open the css or js file url manually in the browser?

**Comment by Tamriel** [comment]
I get no rails output.
The html embeds the js file  `/javascripts/application.js` - which does not exist.
It should be something like `/assets/application.self-8e0a5352ab67ab696a67f0a4296bdf03b93637c63302976a73c58044a5741d2f.js`.

**Comment by wvengen** [comment]
Indeed, I'd expect a hash to be present. Weird. For those new to the asset pipeline, it's explained in the [Rails guides here](http://guides.rubyonrails.org/asset_pipeline.html). I guess the problem also occurs without the reverse proxy (e.g. using an ssh socks proxy)?
Maybe experiment with `config.assets.digest` (and other options mentioned in the Rails guide)?

**Comment by Tamriel** [comment]
Changing the value of `config.assets.digest` does not help. Do you have more ideas?

**Comment by wvengen** [comment]
This is really weird, I have no other ideas at this moment.
Would you be able to provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve)?

**Comment by Tamriel** [comment]
My shared hoster does not allow Docker.
However, we found the solution :-)
One needs to run
`rake assets:environment`
`rake assets:precompile`
after the `rake foodsoft:setup_development`.

**Comment by wvengen** [comment]
Great you found a solution :+1:
If you're running it on a shared host, chances are your default environment is not _development_ but _production_ (environment variable `RAILS_ENV`). In that case, indeed you need to precompile assets as described above. Running Foodsoft as-is, without Docker, is meant to remain a supported production scenario.

**Comment by Tamriel** [comment]
You are right, it is _production_ !
Maybe we should write that somewhere?
By the way, I find the documentation very confusing, since it is scattered over links in the readme.md and the wiki.
Maybe it's a good idea to
- close the wiki and instead list all available documentation pages in the readme.md (like [here](https://github.com/japgolly/scalajs-react#scalajs-react)).
- merge the many setup guides.

**Comment by Tamriel** [comment]
Interestingly, the asset error still appears with ruby 2.4.1, but not with 2.4.3.
