### ISSUE TITLE
foodsoft-dev mailing list spam

### ISSUE THREAD

**Issue by carchrae** [foodcoops/foodsoft#539]
i don't know what you can do, but i've unsubscribed as it is getting more and more spam on the nabble foodsoft-dev.

i realise this isn't the best place for this, but i want to remain in contact and perhaps this can be resolved by turning up some security settings.

**Comment by wvengen** [comment]
Thanks for speaking out. It was really annoying in Dec 2017, it seems to have stopped for now.
Did try to require confirmed email addresses before posting, but either that didn't work, or the spammer was able to confirm an email address.

**Comment by wvengen** [comment]
Closing for now, please reopen if it becomes a problem again.
