### ISSUE TITLE
Deleted `supplier`s show up in `shared_supplier` index

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#546]
The index of `shared_suppliers` shows **deleted** suppliers which have the `shared_supplier_id` set.

**Comment by JuliusR** [comment]
Should we fix this in the [controller](https://github.com/foodcoops/foodsoft/blob/ac11ba1cc1c843e4e07d8179c3028b8b7ac3996c/app/controllers/suppliers_controller.rb#L64), in the [view](https://github.com/foodcoops/foodsoft/blob/ac11ba1cc1c843e4e07d8179c3028b8b7ac3996c/app/views/suppliers/shared_suppliers.html.haml#L20) or should we unset the `shared_supplier_id` on destruction?

**Comment by wvengen** [comment]
That's odd, the shared suppliers view should only list all suppliers present in the shared database, and local suppliers shouldn't interfere with that. Local suppliers connected to a shared supplier that does not exist anymore, are shown, and these might give an error. It's not something that is expected to happen really, but it would be good to handle that gracefully (e.g. by showing an error icon, message, etc.).

**Comment by wvengen** [comment]
I think all shared suppliers should be visible in the shared suppliers index, so not in the controller.
What about filtering out deleted suppliers from [`SharedSupplier.suppliers`](https://github.com/foodcoops/foodsoft/blob/ac11ba1cc1c843e4e07d8179c3028b8b7ac3996c/app/models/shared_supplier.rb#L8)?

**Comment by JuliusR** [comment]
> What about filtering out deleted suppliers from SharedSupplier.suppliers?

Yes, that looks like the _right thing_ here.
