### ISSUE TITLE
Sortable tables

### ISSUE THREAD

**Issue by vitus-a** [foodcoops/foodsoft#560]
Only few columns in some tables are sortable. Why? 
Some columns/tables which would make administration easier, if they are sortable:

- Foodcoop - Members - all columns
- Foodcoop - Ordergroups - "Last activity" and "Last order".
- Administration - Users - "Email" and "Last activity"
- Administration - Ordergroups - "Last Activity"

**Comment by haraldreingruber** [comment]
Hi @vitus-a,

I've taken a look at your improvement suggestion. I was able to make to following columns sortable:

User/Members lists:
- Name
- Email
- Last Activity

Ordergroup lists:
- Name

I am quite happy that I was able to solve it at least partly 😃 I've asked for help (#716) to make "Last activity" and "Last order" also sortable (for Ordergroups).

Do you think this would cover the most important columns for the first version?

**Comment by vitus-a** [comment]
I think so. Sortable "Last activity" and "Last order" would be great to find inactive users. Thanks for your efforts.

**Comment by haraldreingruber** [comment]
This feature is more or less finished, except a final review of the latest changes in PR #716.

Depending on the deployment, it's probably possible to try out the improvements from the branch of my fork...

**Comment by haraldreingruber** [comment]
@vitus-a the improvement is merged to the main branch. Do you know how your deployment is updated? 
Could you test the change once you have the latest version?

**Comment by vitus-a** [comment]
@haraldreingruber the improvement is already implemented in our deployment and seems to work fine. thanks!

**Comment by haraldreingruber** [comment]
@wvengen @paroga I guess this issue can be closed then.
