### ISSUE TITLE
proposal: remove `Dockerfile-dev.yml` as it is broken (and not used by anyone?)

### ISSUE THREAD

**Issue by carchrae** [foodcoops/foodsoft#585]
i spent a lot of time to try and use the development docker.  i eventually got it working, but i have some concerns about the approach in general.

current issues:

* there are some simple fixes, like this: #551 (but actually, it seems a waste to add mailcatcher as a docker, it makes a bigger image rather than running mailcatcher in the rails app container, which adds little bloat)

* resque and redis 4 are broken.  https://github.com/resque/resque/issues/1614 `Error: undefined method 'connect' for Redis:Class (NoMethodError)`  - one fix is to lock redis in the Gemfile with `gem 'redis', '~> 3.3'   # bug with resque https://github.com/resque/resque/issues/1614` - the 'better' fix is upgrade to use `resque 2` - but i didn't explore that. 

* non-standard `Dockerfile-dev` and `docker-compose-dev.yml` are a pain to work with and clutter the root of the project.  would be nicer to have these in a subdir.  

* but at a deep level, why even have a development version of the Dockerfile - it seems wrong to me.  instead, maintain one Dockerfile that is used in both production and development.  this would be much cleaner.  if you need to alter for development, then consider adding some environment variables to do that.

i do have a working environment and could make a PR that addresses all but the last comment, but i am not sure if it is the approach i would choose.

however, i do have an immediate suggestion - we should delete the development one because it is broken.  if a new developer comes to the project, the expectation with a dockerfile is that you can get up and running instantly, but in this case, it took me a lot of time to get it working.  this can scare off new contributors.  as in all OSS projects, cleaning up the detritus makes it easier for new people to join.

**Comment by paroga** [comment]
When I created the production Dockerfile I wanted to delete the development ones to, since they were broken already that time, but @wvengen wanted to keep them if I remember correctly. I'd support deleting them.

**Comment by carchrae** [comment]
i do appreciate that time went into making them and documenting them.  however, without upkeep, they are not good news.  

perhaps i should make a PR that deletes these but also updates the developer getting started docs.  i really like using docker where i can.  now i don't have to install redis, mongo, rethink, mysql, postgres, etc all running on my laptop!

do you use docker when developing foodsoft?  IMHO, if the main developers are not using docker, we should not suggest new developers use docker (but maybe suggest to use mysql/redis in docker if wanted)

**Comment by carchrae** [comment]
i will try to make a 'one-for-all' version of the Dockerfile and it may makes sense to use docker-compose for things like mysql and redis (as that would give people the ability to use a non-container db server with the foodsoft image).  also, building off a rails image (instead of ruby) would make it simpler too.

on the resque/redis thing, it does need some more investigating, because the environment seems to be fine outside docker, so i don't get that.  or maybe i just haven't found the difference yet.

**Comment by wvengen** [comment]
For mailcatcher, I guess the simplest solution would be this (~75MB image):
```diff
diff --git a/config/environments/development.rb.SAMPLE b/config/environments/development.rb.SAMPLE
index e497d441..25f8662c 100644
--- a/config/environments/development.rb.SAMPLE
+++ b/config/environments/development.rb.SAMPLE
@@ -43,7 +43,7 @@ Foodsoft::Application.configure do
   # Mailcatcher config, start mailcatcher from console with 'mailcatcher'
   # Mailcatcher can be installed by gem install mailcatcher
   config.action_mailer.delivery_method = :smtp
-  config.action_mailer.smtp_settings = { address: ENV.fetch('MAILCATCHER_PORT_1025_TCP_ADDR', 'localhost'), port: ENV.fetch('MAILCATCHER_PORT_1025_TCP_PORT', 1025) }
+  config.action_mailer.smtp_settings = { address: ENV.fetch("MAILCATCHER_PORT_25_TCP_ADDR", "localhost"), port: ENV.fetch("MAILCATCHER_PORT_25_TCP_PORT", 1025) }
 
   # Run resque tasks as part of the main app (not recommended for production)
   Resque.inline = true unless ENV['REDIS_URL']
diff --git a/docker-compose-dev.yml b/docker-compose-dev.yml
index c2ec4cdd..96278e38 100644
--- a/docker-compose-dev.yml
+++ b/docker-compose-dev.yml
@@ -22,7 +22,7 @@ services:
       - TEST_DATABASE_URL=mysql2://root:secret@mariadb/test?encoding=utf8
 
   mailcatcher:
-    image: aboutsource/mailcatcher
+    image: tophfr/mailcatcher
     ports:
       - "1080:1080"
 
```
