### ISSUE TITLE
Unexpected behaviour in articles upload

### ISSUE THREAD

**Issue by SomeMichael** [foodcoops/foodsoft#588]
Hi there!

I (already for quite some time) experience an issue when using the option "Delete articles not in uploaded file." when uploading articles for a supllier from a csv file.

I provide this as test data: [Test.zip](https://github.com/foodcoops/foodsoft/files/2607642/Test.zip)

Now doing
![2018-11-22 11_36_51-clipboard](https://user-images.githubusercontent.com/43578183/48897902-a56ad500-ee4b-11e8-91d6-0c63e39a0e4a.png)
after uploading test1.csv before

will result in
![2018-11-22 11_37_10-foodsoft - upload articles](https://user-images.githubusercontent.com/43578183/48897887-9be16d00-ee4b-11e8-926a-88d457b1f76f.png)

That's not what I would expect. In my opinion only article-ID 1 should be deleted.

Could you please check on that?

Thanks for your support! Michael

PS: Example can be found in the Plattsalat foodcoop.

**Comment by wvengen** [comment]
Hmmm, that looks like a bug! Thanks for reporting.
Can someone reproduce this (just to be sure)?

**Comment by JuliusR** [comment]
> Can someone reproduce this (just to be sure)?

Yes, I am able to reproduce this on master and on 4.6.0. In order to observe it, you have to make sure that `article.id` and `article.order_number` do not coincide by accident (as they do on a fresh database with the test data from @SomeMichael). Fix in #670 is ready for review.
