### ISSUE TITLE
add option to make public messages private

### ISSUE THREAD

**Issue by vitus-a** [foodcoops/foodsoft#625]
Somtimes users send mails via foodsoft erroneously not tagged as private. That can be quite embarrassing, in any case they are confusing for others. There is no way to remove them. At least admins should have the ability to delete those from the message area.

**Comment by paroga** [comment]
do you really need a full delete or would be an option to toggle a message between public and private enough?

**Comment by vitus-a** [comment]
You are right - that's the better solution. However, if in future we can see the private messages within foodsoft, it would be nice for users to clean up those by deleting unwanted messages.
In the case of public messages I understand that deletion is problematic.

**Comment by digitalscanner** [comment]
to toggle a message between public and private would be a nice feature for the present 
- we also have a lot of (more or less) private messages in the public list

**Comment by paroga** [comment]
As you might know, there is already #596 to show the private messages in the index pages. I've created a button for toggling privat/public in #626 and deployed it to the Austrian instance. I'd like to have #596 in `master` before doing additional work on top of it.
