### ISSUE TITLE
invoice attachments fail with: NameError (uninitialized constant Invoice::MIME)

### ISSUE THREAD

**Issue by carchrae** [foodcoops/foodsoft#640]
when i tried to attach a PDF to an invoice, causes 500.

```ruby
NameError (uninitialized constant Invoice::MIME):
  app/models/invoice.rb:48:in `valid_attachment'
  app/controllers/finance/invoices_controller.rb:42:in `create'
  app/controllers/application_controller.rb:93:in `set_currency'
  app/controllers/application_controller.rb:81:in `set_time_zone'
```

**Comment by carchrae** [comment]
i suspect that this error is because i haven't installed the documents plugin?

https://github.com/foodcoops/foodsoft/tree/master/plugins/documents#foodsoftdocuments

**Comment by wvengen** [comment]
Thanks for reporting! With tests the mime-types gem is included by capybara, but not in production.
We need to add the gem explicitely to the Gemfile. Will do.
This was introduced in 749791bb7.

**Comment by carchrae** [comment]
ah, thank you.  i was really at a loss as to what i should include to fix this.  much appreciated.
