### ISSUE TITLE
Move from localeapp to crowdin

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodsoft#660]
We've been using localeapp for translating, but its performance is not very well and the Foodsoft instance that would show the changes live has not been working for years. I'd like to move to [Crowdin](https://crowdin.com/project/foodsoft), bringing features like translation memory, glossary, and in-context editing (see also https://github.com/foodcoops/foodcoops.net/pull/34). See [this project](https://crowdin.com/project/foodsoft).

- [x] Setup project on crowdin
- [x] Add instance to global host for in-context editing (https://github.com/foodcoops/foodcoops.net/pull/34)
- [x] Move plugin translations (back) to their own locale files (no need to have one file anymore)
- [x] Add partially translated files from localeapp
- [x] Update wiki documents regarding translation, incl. release instructions (which probably just becomes merging the `l10n_master` branch into `master`)
- [x] Delete localeapp project

**Comment by carchrae** [comment]
@wvengen - i just want to say i very much appreciate the effort you have taken on making foodsoft available to all languages of the world!  i actually looked at foodsoft before you did the translation work, and while it looked promising, the german only meant we could not use it.  so, kudos to you!

**Comment by janklosowski** [comment]
@wvengen Was it difficult to do? I need to follow the same path in my project.

**Comment by wvengen** [comment]
@janklosowski not really. One benefit is that when using multiple locale files, there can be multiple translation files (localeapp only supported one output file). It's great that there is Github-integration, but I had issues integrating that into our flow. (1) there are many incomplete languages that we don't want in our code (yet, as it happens with open source contributions), but you cannot tell Crowdin to only merge back some languages (or perhaps using approval, but I haven't managed to make that work effectively). (2) when the Github-integration is active (to update the master language after code changes), Crowdin insists in making PRs after a translation was entered; somehow that doesn't happen anymore, but I don't really understand why. (3) you can't edit the master language in Crowdin e.g. to fix typo's.

**Comment by wvengen** [comment]
One correction: we are using the Github integration with approval. So anyone can contribute translations, but no PRs will be created by Crowdin. Perhaps in the future we can approve certain languages (and have the PRs autocreated), but until now we're using a [custom script](https://github.com/foodcoops/foodsoft/blob/master/script/crowdin-pull) for that.
