### ISSUE TITLE
Consider initializing resque with file logging

### ISSUE THREAD

**Issue by decentral1se** [foodcoops/foodsoft#674]
> https://github.com/resque/resque#logging

While working on packaging this, I am enabling a resque worker to run under systemd. I'd like to enable logging for this worker to a file (and also have logrotate take care of that). So, I've seen that we need to add some configuration to the `config/initializers/resque.rb` file to specify a log file. Perhaps we could add a `RESQUE_LOG_PATH` environment variable (or whatever) for this purpose?

**Comment by wvengen** [comment]
Would be open to that! In the initializer, one could set it from the environment variable if set.
A PR for this would be readily accepted.

**Comment by decentral1se** [comment]
My need for this went away so will close it off.
