### ISSUE TITLE
Overlong article note causes "internal server error"

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#679]
If you try to upload an article list that contains an overlong note then the foodsoft shows an "internal server error".

Below you can find some more info from the console.

> ```
> ActiveRecord::StatementInvalid (Mysql2::Error: Data too long for column 'note'
> ```

> ```
>   app/controllers/articles_controller.rb:189:in `block (2 levels) in update_synchronized'
>   app/controllers/articles_controller.rb:186:in `each'
>   app/controllers/articles_controller.rb:186:in `block in update_synchronized'
>   app/controllers/articles_controller.rb:175:in `update_synchronized'
>   app/controllers/application_controller.rb:228:in `set_currency'
>   app/controllers/application_controller.rb:216:in `set_time_zone'
> ```

**Comment by wvengen** [comment]
Ouch, either we'll need a validation or increase the `note` column size.

**Comment by vali-um** [comment]
The field definitely needs a length validation that matches the database settings.
There are many other fields with length restricted in the database but no length validation in the model, i will try to comprise a list of them and fix the issue.
But another question: currently notes is a rails string, which corresponds to a varchar of absolute maximum 255 characters in the database. should we change the type to text to enable longer notes (e.g 1000 chars)?

**Comment by kidhab** [comment]
Fixed with #917
