### ISSUE TITLE
OS X 10.13.6 dev install

### ISSUE THREAD

**Issue by voodoo** [foodcoops/foodsoft#712]
UPDATE: Directions seem to work for Ubuntu 18.04.3 (LTS) x64 (though I needed to run db:setup first) Perhaps I'll use a local VM to setup a dev env to kick the tires. Still wondering if there is a  path to Rails 6 
---

I'm following these directions https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_DEVELOPMENT.md

And getting this error running the server (or run any rake command). foodsoft_development

Seems like the 
` rake foodsoft:setup_development`
Command may have worked because I can see the db created ... but with only one table.

`mysql -uroot foodsoft_development`

`mysql> show tables;`

`+--------------------------------+
| Tables_in_foodsoft_development |
+--------------------------------+
| article_categories             |
+--------------------------------+
1 row in set (0.01 sec)`

`bundle exec rails server`

https://gist.github.com/voodoo/0dac68a2ed25524adb831d22c94b7fcc

Has anyone ran into that?

I'd like to setup a coop for a local 2 hub food coop in SA, Texas.

PS: Is there a plan to get to rails 6?

**Comment by wvengen** [comment]
Ouch, that looks like a low-level error. Never seen anything ike this. I've solved other low-level issues sometimes by switching to another Ruby version.

PS: there is some effort to get to Rails 5 first ... see #692

**Comment by wvengen** [comment]
If this remains an issue, feel free to re-open. Closing for now.
