### ISSUE TITLE
deleting an invoice does not clean up order.invoice_id

### ISSUE THREAD

**Issue by carchrae** [foodcoops/foodsoft#718]
today, one of my users accidentally deleted an invoice that was associated with an order.  the invoice deletes just fine, but the order's `invoice_id` property is left pointing to the (now-deleted) invoice.  this means the user is then unable to create a new invoice that refers to the order (since the code thinks it is already linked to one, even though it is a deleted one).

for example, the code below will never populate the select (on the route `invoices/new`) with the order, even if though the order points to a now deleted invoice.

https://github.com/foodcoops/foodsoft/blob/b0ae35f73a498aaafc51b0ea586988fa103edfee/app/controllers/finance/invoices_controller.rb#L35

i am not sure of the best fix for this.  should deleting an invoice set `order.invoice_id` to `nil`? that would seem to be the most precise fix.  i suspect there is some rails magic that would do this, but otherwise, i suppose an active record callback could handle it.

or alternatively, change the linked code above to check if `invoice_id` points to a non-deleted invoice.  but this seems patchy/slow and i wonder if there are other bugs caused by `invoice_id` pointing to a deleted record.

**Comment by wvengen** [comment]
Good one! The invoice_id should indeed be nullified.
