### ISSUE TITLE
release schedule / new release

### ISSUE THREAD

**Issue by carchrae** [foodcoops/foodsoft#725]
the last release was a few years ago.  perhaps it is time to do another one?  or maybe we consider an automated release schedule.  i don't believe we have any breaking changes and i know that many bugs have been fixed on master.

i know both of you (@wvengen and @paroga) work on this project in your spare time, as i do.  and that time comes and goes as you get busy.

**Comment by wvengen** [comment]
http://foodsoft.51229.x6.nabble.com/Upcoming-release-of-Foodsoft-4-7-td5151.html

**Comment by wvengen** [comment]
And so we did!
https://github.com/foodcoops/foodsoft/releases/tag/v4.7.0
https://github.com/foodcoops/foodsoft/releases/tag/v4.7.1

**Comment by carchrae** [comment]
this reminds me, i should try to find time to submit some of the good changes i made to my fork.  one in particular is sending of emails when the order is saved, updated, and settled.   and also i would like to not get too far from the main branch, so i can benefit from your improvements too!
