### ISSUE TITLE
No mention or link to global hosting

### ISSUE THREAD

**Issue by webdog-rich** [foodcoops/foodsoft#738]
The below page and related pages mention global hosting multiple times, but there is no actual url for the global hosting platform. Does it exist?

[Global Hosting](https://foodcoops.github.io/global-foodsoft-platform/)

**Comment by paroga** [comment]
> Does it exist?

yes, you can find details about the hosting at https://foodcoops.net/foodsoft-hosting/ and about the demo at https://foodcoops.net/demo/

what information did you not find?

**Comment by webdog-rich** [comment]
I guess what I am asking is: is there a hosted version of the software that I can sign up to use? Or do I need to host it myself for my own needs? The page [https://foodcoops.net/foodsoft-hosting/](https://foodcoops.net/foodsoft-hosting/) mentions that there is a global hosting platform but there is no link to this, only a link the the demo. Am I missing something here?

From the website:
"People from several food cooperatives in Europe came together to start a global hosting platform for everyone. It is maintained by a few volunteers from different countries, and hosting costs are paid for by (yearly) donations. They’d be happy to welcome you on board."

**Comment by paroga** [comment]
> is there a hosted version of the software that I can sign up to use?

yes, please use the contact button to write an email and include the following informations:

* Name of your foodcoop
* Short name (for use in the web address)
* Contact person (name + email address)
* Fallback contact person (name + email address)
* Homepage (if any)
