### ISSUE TITLE
Review stock_events migration for 4.7

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodsoft#768]
When deploying latest master to the foodcoops.net instance (foodsoft_latest), the following migration error occured:

```
I, [2020-09-06T07:54:13.378573 #6]  INFO -- : Migrating to CreateStockEvents (20181204070000)
== 20181204070000 CreateStockEvents: migrating ================================
-- rename_table(:deliveries, :stock_events)

StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'stock_events' already exists: RENAME TABLE `deliveries` TO `stock_events`
Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'stock_events' already exists: RENAME TABLE `deliveries` TO `stock_events`
(...)
/usr/src/app/db/migrate/20181204070000_create_stock_events.rb:6:in `change'
```

Rolling back and re-migrating didn't fix it.
Check that migrations on existing installations work before releasing.

**Comment by wvengen** [comment]
Related to #754.

**Comment by wvengen** [comment]
I do remember a force-push on master in the past days, if that was a migration then it may not be a real issue (only foodcoops.net).

**Comment by paroga** [comment]
how are the migrations handled on foodcoops.net? Is it possible that the migration only executed partly? If the migration happened then `20181204070000` should be in the `schema_migrations` table, otherwise how can the `stock_events` table exist already? Did you try to fix something manually? I have no explaination why `deliveries` looks like a half migrated `stock_changes` (which is missing)

**Comment by paroga** [comment]
I forgot to test the trivial case where no delivery or stock taking exist. :roll_eyes:  Thanks for the report.
Fixed with 00bb10d14af4a7a052ab68ca9cd613c039172830

**Comment by wvengen** [comment]
Thanks for fixing!
On foodcoops.net this doesn't yet succeed. Locally the migration runs fine, though (no stock_changes).

**Comment by wvengen** [comment]
I'd be ok recreating the foodcoops.net latest demo database. (`stock_events` already exists, must have been a partial migration)
