### ISSUE TITLE
release 4.7.1

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#777]
Can we schedule a bugfix release 4.7.1? There are at least two foodcoops that are waiting for #773 .

- [x] Plan
  - [x] Create [milestone](https://github.com/foodcoops/foodsoft/milestone/19)
  - [x] Select bugs to target
  - [x] Pick freeze date, after which no big changes occur until release
  - [x] Pick release date (and update milestone)
   - [x] Start writing [release notes](https://github.com/foodcoops/foodsoft/wiki/Release-notes#foodsoft-471)
- [x] Communicate to mailing-list foodsoft-dev@
- [x] Merge, test, check, double check
  - [x] <del>#778</del> (postponed for 4.7.2)
- [x] At release date
  - <del>Merge any new translations in the source tree (run `script/crowdin-pull`, commit changes but not new files)</del>
  - [x] Make sure tests are ok (GitHub actions)
  - [x] Finalise release notes and update [`CHANGELOG.md`](https://github.com/foodcoops/foodsoft/blob/master/CHANGELOG.md)
  - [x] Bump [`VERSION`](https://github.com/foodcoops/foodsoft/blob/master/VERSION) (use `X.Y.Z` version number)
  - [x] Commit with message "_Bumped new version: X.Y.Z_"
  - [x] Tag `vX.Y.Z`
  - [x] Update tag `latest-release` (for download links)
  - [x] Bump VERSION file to `vX.Y.99`, commit with message "_continue development after release_" to `master`.
  - [x] Check tags `latest-release`, `X.Y.Z` and `X.Y` are building on [Docker](https://hub.docker.com/r/foodcoops/foodsoft/builds/)
- [ ] Announce
  - [x] on mailing-list foodsoft-announce@
  - [ ] on [Twitter](https://twitter.com/foodsoftdev)
  - [ ] on [sourceforge news](https://sourceforge.net/p/foodsoft/news/)
  - [ ] on other places, if you like
- [ ] Celebrate!

**Comment by JuliusR** [comment]
Some days have passed since 4.7.0, and not many bugs have been reported. I would like to deploy the fix for #772 soon because the bug disables an important feature of the foodsoft (considering my foodcoop).

From my point of view, there can be a 4.7.1 release based on the current master (4fa5c4e00d86c30e849f3e0430f0fb2671128b5c). Would you like to omit some of those fixes, or are there any additional bugs you would like to include in an upcoming 4.7.1?

I suggest a freeze and release date around next weekend, i.e., October 24th.

I have never created a release before, but I think I can make it based on the [instructions](https://github.com/foodcoops/foodsoft/wiki/Creating-a-release). Translations can be skipped, I guess. Anyone willing to help?

What do you think about my suggestions? I will wait for your feedback before proceeding.

@wvengen @paroga

**Comment by paroga** [comment]
IMHO we can just use the `master` branch. I've created #778 for a found regression, which we should include in 4.7.1. Unfortunately I had no time to create a test for it and therefore didn't pushed it to master.

**Comment by wvengen** [comment]
I'll be happy to do a new release.
Not sure about going to `master` instead of releases. I like the idea that users can use features sooner and more immediate feedback on features. But when an issue occurs, then we must fix it, releases are tested more. Personally I would not be ready for that.

**Comment by JuliusR** [comment]
> Not sure about going to `master` instead of releases.

This is not what I had in mind. I was talking about including all of the recent changes from master for 4.7.1 (rather than cherry-picking individual bug fixes).

**Comment by JuliusR** [comment]
> I suggest a freeze and release date around next weekend, i.e., October 24th.

Sorry, I missed that date because I was too busy. My new suggestion is: Let us get #778 done, and release 4.7.1 as soon as possible.

**Comment by JuliusR** [comment]
My foodcoop is craving for 4043433539f34b880bec8826d2f29f9137412ef4. However, I do not know how to handle #778, which is blocking this release. I am seeing three options:

1. We test and merge #778 soon. I can help if you explain me what to do, but I can not do this on my own.
2. We postpone #778 for 4.7.2, and release 4.7.1 based on the [current master](https://github.com/foodcoops/foodsoft/tree/4043433539f34b880bec8826d2f29f9137412ef4) now.
3. We wait some more time before we release 4.7.1 including #778, but we deploy deploy foodcoops.net based on the current master once.

My preference is option 2. What do you think, @wvengen and @paroga?

**Comment by JuliusR** [comment]
I am proceeding with option 2.

**Comment by wvengen** [comment]
Super, thank you!
Sorry for the delay in answering.

**Comment by JuliusR** [comment]
I need help with the docker setup. My current status is #793, and docker hub [shows new builds](https://hub.docker.com/r/foodcoops/foodsoft/builds). However, I do not know how to manage the docker-hub tags. 

* Do I need additional (docker-hub) secrets?
* Should we [setup github actions](https://docs.docker.com/ci-cd/github-actions/) for managing tagged docker images?

I will contact you personally for interactive help.

**Comment by wvengen** [comment]
I think if you tag on Foodsoft, Docker hub does its thing automatically. Make sure to make the `v4.7.1` tag, and to bump `latest-release` (force-push that one).

**Comment by JuliusR** [comment]
My plan was to test the full [docker-compose setup](https://github.com/foodcoops/foodcoops.net) on my machine before finalizing the release. In order to make it available, I created and pushed the tag [4.7.1-rc0](https://github.com/foodcoops/foodsoft/releases/tag/v4.7.1-rc0). I [can not find that tag on docker hub](https://hub.docker.com/r/foodcoops/foodsoft/tags), though. Maybe docker hub does not like the `-rc0` suffix in the tag name?

Let us first finish our discussion in #793. Then I will try to test the docker-compose setup with that outcome.

**Comment by JuliusR** [comment]
I have tested the migration from 4.7.0 to [4.7.1-rc](https://hub.docker.com/r/foodcoops/foodsoft/tags?name=4.7.1-rc) locally. I was using the full docker-compose setup with one foodsoft instance (foodsoft_demo) in a multicoop environment.

**Comment by JuliusR** [comment]
I have created the tag [v4.7.1](https://github.com/foodcoops/foodsoft/tree/v4.7.1), and I have updated the tag [latest-release](https://github.com/foodcoops/foodsoft/tree/latest-release). The [docker-image builds](https://hub.docker.com/r/foodcoops/foodsoft/builds) are in progress. Naming can be improved, but everything seems to work.

I suggest to publish the following announcement text:

> Hello,
> 
> Foodsoft 4.7.1 has been released. <a href="https://github.com/foodcoops/foodsoft">Foodsoft</a> is an online software for running a non-profit foodcoop (a collective do-it-yourself supermarket) with a product catalog, order cycle, accounting, and tasks.
> 
> This is a bugfix release. It fixes several minor issues, and it fixes the article search in the external database. See the <a href="https://github.com/foodcoops/foodsoft/blob/v4.7.1/CHANGELOG.md#foodsoft-471">changelog</a> for details.
> 
> If you need help upgrading your instance, or other support, please contact the <a href="http://foodsoft.51229.x6.nabble.com/foodsoft-discuss-f5.html">foodsoft-discuss mailing-list</a>.
> 
> Best,
> Julius
> 
> <a href="http://foodsoft.51229.x6.nabble.com/foodsoft-discuss-f5.html">foodsoft-discuss</a> | <a href="https://github.com/foodcoops/foodsoft">github</a> | <a href="http://www.foodcoops.net/">foodcoops.net</a> | <a href="https://twitter.com/foodsoftdev">@foodsoft.dev</a>
> 
> P.S. Please feel free to share this announcement to others who might be interested!

**Comment by wvengen** [comment]
Thanks, @JuliusR 🎉 
I invite you to send this message to the foodsoft-announce mailing-list, as you've made this happen.

**Comment by wvengen** [comment]
I've lost access to the Twitter account, unfortunately. I need to see if I can dig up the credentials from some old place (hopefully - I lost access to the domain used for the emailaddress).

**Comment by JuliusR** [comment]
> I've lost access to the Twitter account, unfortunately. I need to see if I can dig up the credentials from some old place (hopefully - I lost access to the domain used for the emailaddress).

Ah, I see. I will omit the twitter link in the accouncement then. Let us hope you can re-gain access.
