### ISSUE TITLE
disable merge commits via github

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#780]
In response to https://github.com/foodcoops/foodsoft/pull/773#issuecomment-710806575 I suggest to disable merge commits.

The repository has a tab called "Settings" (visible to owners), where we can disable the first of the following checkboxes:

![Screenshot_2020-10-17 JuliusR foodsoft](https://user-images.githubusercontent.com/2647805/96336675-bba65d80-1081-11eb-9584-b59c4e69c5a6.png)

**Comment by paroga** [comment]
i changed the settings. thanks for the info.
