### ISSUE TITLE
Gebindegrößenproblem, Bug?

### ISSUE THREAD

**Issue by rolfschr** [foodcoops/foodsoft#786]
Hi,
this is in german, I guess that's fine.

Wir haben in letzter Zeit ein Problem mit der Bestellung bei einem best. Lieferanten bei best. Artikeln bzw. deren Gebindegröße. Für uns ist nicht offensichtlich erkennbar, warum Brötchensorte A mit Gebindegröße 5 anders behandelt wird als Brötchensorte B mit Gebindegröße 5. Beim Einstellen der Bestellung bzw. beim Bestellen ist noch alles gleich, aber sobald die Bestellung beendet ist, wird die Gebindegröße bei einem Brötchen automagisch auf 1 gesetzt. Siehe PDF.

[Brötchenchaos_20201110.-1.pdf](https://github.com/foodcoops/foodsoft/files/5540740/Brotchenchaos_20201110.-1.pdf)

Die Mitglieder haben 5 Brötchen bestellt, aber im Matrix-PDF steht nur noch 1.
Gerne gebe ich mehr Details weiter.

Danke,
Rolf

**Comment by wvengen** [comment]
Hi, thanks for your detailed error report. Indeed it looks like the `unit_quantity` was changed from `5` to `1` after the order was closed. Can you check the `article` to see if it the `unit_quantity` was changed - as well as the `order_article` (I think that can be viewed and edited e.g. in the receive screen).

**Comment by rolfschr** [comment]
Hi wvengen,

thanks for the hints. We did check and did not see any changes. Interestingly, the problem did not occur recently. We have updated (with the same data) some of our articles but not all. Not sure what happened in the meantime but as I said, we currently cannot not reproduce the issue. I'm closing this here for know unless the resurfaces again.
