### ISSUE TITLE
Increase readability of IBANs by adding whitespaces 

### ISSUE THREAD

**Issue by mariandl** [foodcoops/foodsoft#821]
Request from ["Michael"](https://forum.foodcoops.at/t/leserlichkeit-von-iban/4718/3):

To increase the readabiliy of IBANs it can be useful to display them seperated by whitespaces:

- IBAN: EU10 0000 0000…

**Comment by twothreenine** [comment]
Tried to do it [in this commit](https://github.com/twothreenine/foodsoft/commit/85f26a8d9555289f38d9919178268c8c66072cc3) in my fork.
Important note: I couldn't test it for finance/bank_transactions/show.html.haml

Seems I cannot create a pull request for a specific commit, only a branch?!
Also I'm very new to Ruby, so please check it carefully
