### ISSUE TITLE
Localisation typo

### ISSUE THREAD

**Issue by fruestueck** [foodcoops/foodsoft#837]
There is a minor typo in the german localisation on the "Mehrere Konten aktualisieren" page (url: `/finance/transactions/new_collection`) where it writes "Bestellgrupppe".

Corresponding line 924 in file `/config/locales/de.yml`

**Comment by wvengen** [comment]
Thanks for the correction!
This can be corrected in our translation system, see [the wiki](https://github.com/foodcoops/foodsoft/wiki/Translation).

**Comment by wvengen** [comment]
I've changed this in the translation system (Crowdin), and it should be picked up with the next release.

**Comment by paroga** [comment]
updating it in the translation system does not help with a "rolling release setup". we need to get it into this repository...

**Comment by wvengen** [comment]
Done in dee12418882353a863a5cc03a764cf3bd6e367d1.
