### ISSUE TITLE
Transport costs are not accounted anymore

### ISSUE THREAD

**Issue by twothreenine** [foodcoops/foodsoft#861]
I just noticed that recently ordergroups are accounted their order sum _without_ the distributed transport cost.
On the confirm page, the amounts are still displayed including the transport costs, but the transactions then created don't include them!

In our @foodcoopsat deployment, it still worked on March 2nd, but didn't on March 14th, also it doesn't work with the current master version here.

**Comment by paroga** [comment]
the problem is easy to fix: `price` needs to be changed to `total` at https://github.com/foodcoops/foodsoft/blob/007ff70c486be5d93cb189fa4e13327270436e62/app/models/order.rb#L393-L396 and we need a test for that too

**Comment by twothreenine** [comment]
I wish this would be fixed soon, as the PR is already there.
We have many orders waiting to be accounted and most foodcoops won't even have noticed this bug and accounted without transport costs

**Comment by decentral1se** [comment]
This does seem like kind of a critical bug @twothreenine :worried:
