### ISSUE TITLE
bundle install fails due to yanked version of locked mimemagic

### ISSUE THREAD

**Issue by lentschi** [foodcoops/foodsoft#864]
The command `bundle install` on a fresh install fails with the error message:

```
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the
author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to install.
```

This is due to the `mimemagic` gem having been yanked in the version locked by `Gemfile.lock` (0.3.5):
https://rubygems.org/gems/mimemagic/versions

See also:
https://github.com/rails/rails/issues/41750#issuecomment-810808957

**Comment by wvengen** [comment]
Ouch, that is pretty serious.
Also the cause of failing docker hub [build](https://hub.docker.com/repository/registry-1.docker.io/foodcoops/foodsoft/builds/06707427-0054-485b-a7f9-ffeb95254986).
