### ISSUE TITLE
apply for open-source plan on docker hub

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#883]
We are currently using a "free team plan" for [foodcoops' docker hub organization](https://hub.docker.com/u/foodcoops). According to a recent announcement, the [autobuild feature will be removed from docker's free plans](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/). The deadline is June 18, 2021.

I think that we do need the autobuild feature. I am not 100 % sure, though. Who can clarify?

There is the possibility to [apply for an open-source plan](https://www.docker.com/community/open-source/application). I have not checked the conditions yet. Who can do some research here?

**Comment by decentral1se** [comment]
I don't really have a clue but as far as I see in the https://github.com/foodcoops/foodsoft/actions listing, there is no integration to build the containers? Are they built and pushed by hand? In that case, it doesn't matter and you wouldn't need to apply for a plan. The plans are currently designed to limit how many images you can pull (rate limiting) as far as I understand.

**Comment by wvengen** [comment]
I have applied some time ago, and today got a response, in which confirmation was asked.

>
> Docker remains highly committed to providing a platform where the non-commercial open source developers can continue collaborating, innovating and pushing this industry into new directions.  For the approved, non-commercial, open source namespaces, Docker will suspend data pull rate restrictions, with no egress restrictions applying to any Docker users pulling images from those namespaces
> 
> ## Open Source Qualification Criteria
> 
> To qualify the Publisher namespace for the Open Source Program status, the Publisher namespace -
> 
> -  Must be shared in public repos
> -  Is not funded by commercial company or organization
> -  Meets the Open Source Initiative definition (defined here), including definitions for 
> -  Free distribution, source code, derived works, integrity of source code, licensing and no tolerance for discrimination 
> -  Distributes images under an OSI approved open source license
>
> The process for applying for Open Source status is summarized below -
> 
> ## Review and approval
> -  The Publisher submits the Open Source Community Application form. 
> -  Docker reviews the form, and determines if the Publisher qualifies for open source status.
> -  If Docker approves the Publisher’s application, Docker will waive the pull rate policy for the Publisher’s namespace, for a period of one year
> -  Every 12 months, Docker will review the Publisher’s namespace, to verify that the Publisher continues to qualify with the Docker Open Source Program criteria, and will extend the Open Source Program status for another 12 months.  
> -  Docker may, at its discretion, also review eligibility criteria within the 12-months period, and, depending on the changes of Publisher’s compliance with program criteria, revise the Publisher’s Open Source Program status
> -  The Publisher may have other namespaces, that either partially comply or do not comply with open source policy requirements, and therefore, will not qualify for open source status
>
> ## Joint Marketing Programs
> 
> While the Publisher retains the Open Source project status, the Publisher agrees to -
> 
> -  Become a Docker public reference for press releases, blogs, webinars, etc
> -  Create joint blogs, webinars and other marketing content 
> -  Create explicit links to their Docker Hub repos, with no ‘wrapping’ or hiding sources of their images
> -  Include information about Docker on the website and in documentation

**Comment by wvengen** [comment]
My proposed response:

> - Must be shared in public repos  -> https://github.com/foodcoops/foodsoft
> - Is not funded by commercial company or organization  -> we are all volunteers, the global platform is funded by donations, see https://foodcoops.net/global-foodsoft-platform/
> - Meets the Open Source Initiative definition (defined here) -> AGPL-3+, see https://github.com/foodcoops/foodsoft/blob/master/LICENSE.md
> - Distributes images under an OSI approved open source license -> since the source code is covered by AGPL-3+, this also applies to the Docker images.
>
> Regaring the marketing programs:
> - Become a Docker public reference for press releases, blogs, webinars, etc  -> ok
> - Create joint blogs, webinars and other marketing content  -> as we are all volunteers with more work than hours, I'm not sure that we can commit to writing original content for Docker, but if desired we can cooperate
> - Create explicit links to their Docker Hub repos, with no ‘wrapping’ or hiding sources of their images  -> https://github.com/foodcoops/foodsoft#readme
> - Include information about Docker on the website and in documentation  -> https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_DEVELOPMENT_DOCKER.md and https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_PRODUCTION.md

**Comment by wvengen** [comment]
Mail sent.

**Comment by wvengen** [comment]
We have been approved!
>Welcome to the Docker Open Source Program!  We are very excited to have you as a part of our great community.  We have allow-listed your namespace "foodcoops" and this should come into effect in the next week or so. With this allowed-listing, the Docker data pull rate policies that went into effect last November, will not apply to the users pulling images from your namespace.  
>
> Thank you for your support for Docker and your open source contributions.
