### ISSUE TITLE
Internal Server Error when trying to open our Foodsoft page

### ISSUE THREAD

**Issue by tomopencs** [foodcoops/foodsoft#888]
Hi, 
I am not sure if this is the right place for this issue: when I try to open our page (plattsalat), I get this error message:

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

On https://app.foodcoops.net/ the same error message appears.

Normally it wouldn't be a big problem, but today is the Schokofahrt Ordering Deadline (https://schokofahrt.de/) and our members must order today.

Thanky a lot and greetings

Thomas

**Comment by decentral1se** [comment]
Hi @tomopencs do you have access to the server and can you provide us with information from the Foodsoft logs?

**Comment by tomopencs** [comment]
Heyho, it works again without any problem. I am not sure if I could provide logs, I have no idea where to look for them, unfortunately.

**Comment by kidhab** [comment]
This was a problem with the global foodsoft hosting's setup. It should be fixed in the meantime.

@tomopencs: Such issues are not related with the foodsoft itself. You can use the support mailinglist for such problems. Just write an email to support@list.foodcoops.net
