### ISSUE TITLE
rvm vs. rbenv

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodsoft#899]
The [instructions](https://github.com/foodcoops/foodsoft/blob/master/doc/SETUP_DEVELOPMENT.md) recommend `rvm`. On debian, I prefer [`rbenv`](https://packages.debian.org/bullseye/rbenv) because I can install it with `apt`.

Is there any reason to prefer `rvm` over `rbenv`?

**Comment by wvengen** [comment]
Not really. At the time, `rvm` seemed to be slightly more used (but I may have been biased).
Would it be confusing to document both? I'm also ok with switching the docs to `rbenv`.

Actually, I'm using Debian's `rbenv` as well (even though its data files are outdated, and I need to manually add new Ruby versions to the datadir).
