### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by qq7** [foodcoops/foodsoft#926]
I'm rebuilding the TurnKey Linux Foodsoft appliance against v17.0 (Debian 11).

Since you're not tagging releases anymore, how would you suggest determining the stable release that's suitable for production?

**Comment by decentral1se** [comment]
@qq7 releases are still tagged:

> https://github.com/foodcoops/foodsoft/tags

**Comment by wvengen** [comment]
It's indeed time for a new release, thanks for the headsup!

**Comment by qq7** [comment]
@wvengen thank you for your elaboration and the maintenance of Foodsoft.
