### ISSUE TITLE
API - documentation and access

### ISSUE THREAD

**Issue by leomayer** [foodcoops/foodsoft#976]
I follow the documentation of the `doc/swagger.v1.yml` and if I understand it correctly than e.g.
```
https://app.foodcoops.at/myFoodcop/api/v1/orders
```

should return `200` if I'm logged in. I test in a browser (Chromium) and I'm in another tab logged in. Nevertheless I get as response
```
{
"error": "invalid_token",
"error_description": "Der Access Token ist nicht gültig/korrekt"
}
```
meaning that the access token is invalid. What is wrong? Or what do I have to specify additionally in the API request?

**Comment by wvengen** [comment]
The Foodsoft API uses OAuth to get a token (this is not the cookie-based session token that is used when you access the Foodsoft application).

See also https://github.com/foodcoops/foodsoft/blob/master/doc/API.md
