### ISSUE TITLE
haml upgrade breaks deface

### ISSUE THREAD

**Issue by Viehlieb** [foodcoops/foodsoft#980]
We found out that haml >= 6.0 breaks the plugins capabilities to alter views.
The deface gem depends on haml, but apparently does not work with haml >= 6.0. No Error thrown, but no functionality given. The documentation says it should work with haml. 

Alterations that have been done inside plugin's engine.rb, e.g. add another NavItem work regardless. Only .deface files are problemativ.

suggested solution
downgrade haml to 5.X and deface will work again

**Comment by kidhab** [comment]
Reopening.
Sorry, my comment at the other repository closed this issue automatically.

**Comment by kidhab** [comment]
[Issue](https://github.com/spree/deface/issues/237) at deface issue tracker.
